# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

  target 'Info Center for League of Legends' do
    use_frameworks!
	  workspace 'project'

	  # Pods for Info Center for League of Legends
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Auth'
    pod 'AFNetworking'
    pod 'BEMSimpleLineGraph', :git => 'https://github.com/Boris-Em/BEMSimpleLineGraph.git', :branch => 'feature'
    pod 'MBCircularProgressBar'
    pod 'SGSStaggeredFlowLayout'
    pod 'XCDYouTubeKit'
    pod 'AMPopTip'
    pod 'JSBadgeView'
    
    # pod 'FLAnimatedImage'
    # pod 'M13ProgressSuite'

  target 'Info Center for League of LegendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Info Center for League of LegendsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
