# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Info Center for League of Legends' do
	# Comment this line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
	workspace 'project'

	# Pods for Info Center for League of Legends

	pod 'AFNetworking'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Messaging'
	pod 'Firebase/RemoteConfig'
	pod 'MBCircularProgressBar'
	# pod 'SGSStaggeredFlowLayout'
	# pod 'XCDYouTubeKit'
	# pod 'JSBadgeView'
	# pod 'AMPopTip'
	# pod 'BEMSimpleLineGraph'
	
	# pod 'FLAnimatedImage'
	# pod 'M13ProgressSuite'

	target 'Info Center for League of LegendsTests' do
		inherit! :search_paths
		# Pods for testing
	end

	target 'Info Center for League of LegendsUITests' do
		inherit! :search_paths
		# Pods for testing
	end
end